### ISSUE TITLE
Change node color

### ISSUE THREAD

**Issue by Nid989** [ChrisDelClea/streamlit-agraph#22]
The color of nodes is not changing nor that of edges, I tried modifying the argument under config for node but nothing changed. Any reason why?

**Comment by myedibleenso** [comment]
@Nid989 , this works for me.  If you need more fine-grained control (ex. only nodes A, B, and C should have color Y), you'll need to specify the color at `Node` creation.  The same can be done for edges at `Edge` creation time.  

Can you please include a code snippet?
