### ISSUE TITLE
NodeNotFound: Source (2, 57) is not in G

### ISSUE THREAD

**Issue by wgong** [ChrisDelClea/streamlit-agraph#23]
this line at https://github.com/ChrisDelClea/streamlit-agraph/blob/master/examples/ego_graph.py#L35

should be changed to (2nd arg is Id
```
hub_ego = nx.ego_graph(G, most_connected_node[0])
```

**Comment by ChrisDelClea** [comment]
thank you, @wgong . I will update it soon.
