### ISSUE TITLE
Strange behavior when clicking a node or edge

### ISSUE THREAD

**Issue by myedibleenso** [ChrisDelClea/streamlit-agraph#26]
Hi.  Thanks for this useful component!  

I've noticed that if I click a node (as opposed to clicking and dragging), it seems to trigger a UI rewrite.  I saw that there was a merged PR related to tracking clicks ( #12 ) and thought the (undocumented) feature might relate to what I'm seeing.   Is there a way I can disable this behavior?  I'd like to be able to drag nodes around, but I don't want a click event to trigger the UI to re-render top-down.

**Comment by myedibleenso** [comment]
I'm guessing it relates to including `.setComponentValue` https://github.com/ChrisDelClea/streamlit-agraph/commit/98af62ea930ecb4ecaebd613313739d51bcd53c0#diff-88ab80ff923981d946011e0f62e505fde65a7c455b6241c7e87756401a333173


Detecting and responding to clicks seems useful, but I'm not sure how to detect the click in this case.  Are there any examples of using this feature?

**Comment by ChrisDelClea** [comment]
Hey @myedibleenso ,

i see. Seems to be an issue indeed. One really had to fix the onNodeClick value. 
As i am kinda busy these days, i'd really appriciate if you find a fix, you push it! 

Best regards
Chris

**Comment by ChrisDelClea** [comment]
Should be fixed, @myedibleenso. Can you double check and give me a ping? If I don't hear from you, I assume its resolved.

**Comment by thisisanameforsure** [comment]
I am still seeing this issue
