### ISSUE TITLE
Click events

### ISSUE THREAD

**Issue by TudorAndrei** [ChrisDelClea/streamlit-agraph#27]
Hi.

Is there a way of selecting a node and then use the information saved in it to display it in another streamlit container?

I see that in the `AgraphComponent.tsx` there is `onClick` functionality but how would this be used, and where would the contents be saved?

**Comment by ChrisDelClea** [comment]
Hi @TudorAndrei ,

you can have a return value from the AgraphComponent.tsx and receive it in the __init__.py and pass it back from the component. However, you'd have to implement the functionallity yourself. Does that help?

Best regards
Chris

**Comment by ChrisDelClea** [comment]
@TudorAndrei, made some major update. You get the id of the element back with `return_value = agraph(nodes, edges, config=config)`. If this is the kinda information you are talking about, you can than use the id as you wish.

**Comment by TudorAndrei** [comment]
> @TudorAndrei, made some major update. You get the id of the element back with `return_value = agraph(nodes, edges, config=config)`. If this is the kinda information you are talking about, you can than use the id as you wish.

This is what I was looking for. Tyvm

**Comment by mayurankv** [comment]
Is it possible to also have click events for edges?
