### ISSUE TITLE
how to change the background color

### ISSUE THREAD

**Issue by siam1991** [ChrisDelClea/streamlit-agraph#29]
hi, 
I'm using this tool to develop a knowledge graph demo,but I want to change the graph background color, which parameter I should use?

**Comment by ChrisDelClea** [comment]
Hi @siam1991,

on a quick glance in the docu (https://danielcaldas.github.io/react-d3-graph/docs/index.html) i did not find a way to do it. 
However, a user asked a similar question on github. 
You would acutally have to wrap the streamlit-agraph component in a div (https://codesandbox.io/s/react-d3-graph-small-forked-hkmpq?file=/src/App.js:142-404) . 

Best regards
Chris
