### ISSUE TITLE
"directed" parameter is not working

### ISSUE THREAD

**Issue by ViniciusgCaetano** [ChrisDelClea/streamlit-agraph#34]
Setting directed equals True or False results in the arrowheads being showed in the graph.

**Comment by ViniciusgCaetano** [comment]
`import streamlit as st
from streamlit_agraph import agraph, Node, Edge, Config

st.title('Opa')

nodes = []
edges = []

nodes.append(Node(id="A1", 
                   size=5)
            ) # includes **kwargs


nodes.append( Node(id="A2", 
                   size=5) 
            )

edges.append( Edge(source="A1",
                   label="", 
                   target="A2",
                   type="-"
                   # **kwargs
                   )
            ) 

config = Config(directed=False,
                width=1000, 
                height=1000, 
                # **kwargs
                ) 

return_value = agraph(nodes=nodes, 
                      edges=edges, 
                      config=config,
                      )`



Results on that

![image](https://user-images.githubusercontent.com/57851959/199854783-9a1ad6c6-42cf-47ca-bf13-b04f7661dbfa.png)

The result should be a line without the arrowhead

**Comment by ChrisDelClea** [comment]
Hey @ViniciusgCaetano ,

did you figure it out yet? Actually it took me a few secs to figure it out myself.
The solution is actually quite simple. Just pass edges configs to the `config` with ` "arrows":"none" `.

```python
config = Config(width=750, height=750, edges={"arrows":"none"} ) 
```

If it solves your problem, feel free to close the issue.
