### ISSUE TITLE
Documentation resource

### ISSUE THREAD

**Issue by taws34** [ChrisDelClea/streamlit-agraph#38]
Is there a solid documentation resource?  

I'm trying to find a current list of methods for the config / nodes / edges.

edit:  I have used https://danielcaldas.github.io/react-d3-graph/docs/index.html#graphconfig but I find the configurations do not match what agraph uses.     Node 'symbolType' vs 'shape', for instance.

**Comment by ChrisDelClea** [comment]
Dear @taws34 ,

we moved from d3-graph to [react-graph-vis](https://github.com/crubier/react-graph-vis) . 
Please check it out.

**Comment by ChrisDelClea** [comment]
Just check also the `ConfigBuilder` Class I just released. You can play with it in the Demo app linked in the README.
